services:
  - type: web
    name: adorona-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: MONGODB_URL
        value: "mongodb+srv://bhoomi:bhoomi23@cluster0.wcbjoil.mongodb.net/arodona_db?retryWrites=true&w=majority&appName=Cluster0"
      - key: DATABASE_NAME
        value: "arodona_db"
      - key: SECRET_KEY
        value: "your-super-secret-key-change-in-production-2024"
      - key: ENVIRONMENT
        value: "production"
      - key: SUPER_ADMIN_SECRET_KEY
        value: "super-admin-secret-key-2024"
      - key: BACKEND_URL
        value: "https://adorona.onrender.com"